---
title: "Mi dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: yeti
    social: [ "menu" ]
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)

```

Básicos
========================================================================

Row
-----------------------------------------------------------------------

### Chart A

```{r}
data <- read.csv("https://raw.githubusercontent.com/plotly/datasets/master/school_earnings.csv")

data$State <- as.factor(
  c('Massachusetts', 'California', 'Massachusetts', 'Pennsylvania', 
    'New Jersey', 'Illinois', 'Washington DC', 'Massachusetts', 
    'Connecticut', 'New York', 'North Carolina', 'New Hampshire', 
    'New York', 'Indiana', 'New York', 'Michigan', 'Rhode Island', 
    'California', 'Georgia', 'California', 'California'))

fig <- plot_ly(
  data, x = ~Women, y = ~Men, text = ~School, 
  type = 'scatter', mode = 'markers', 
  size = ~Gap, color = ~State, colors = 'Paired',
  marker = list(opacity = 0.5, sizemode = 'diameter')
) %>% 
  layout(
    title = 'Gender Gap in Earnings per University',
    xaxis = list(showgrid = FALSE),
    yaxis = list(showgrid = FALSE),
    showlegend = FALSE
)

fig
```


### Chart B

```{r}

```

Row {data-width=350}
-----------------------------------------------------------------------


### Chart C

```{r}

```

